### PR TITLE
feat: Add RSS for affine.pro

### PR DESCRIPTION
**Pull request by asad0206**
Issue : #143 

-*Added RSS support for the website*
Utilized RSS node js package which is a lightweight and independent package

image

You can see the example ss attached.

Please check the Pull Request and allow for the merge, In case of any issue please contact me. Thank you!

### CODE REVIEW

**Comment by asad0206** [comment]
@pengx17 Please check this PR and merge the same. If the code is upto ur standards. Thanks

**Review by lawvs — CHANGES_REQUESTED** [review]
Please remove `package-lock.json`

**Review by pengx17 — CHANGES_REQUESTED** [review]
Thanks for your contribution!
Some changes that need to be made before merging:
1. All files in content are static thus there is no need to have a dynamic API handler for RSS. Can you instead write a new script in `/generation` and run it in github action instead?
2. No need to parse file with gray-matter again. All content's metadata is already parsed and in json format.
3. I think you can just generate RSS for the blog files, excluding the templates and changelog.

**Comment by asad0206** [comment]
Okay give me some time and I will do the requested changes ASAP. Sorry for the delay

**Pull request closed without merging**
